-- MySQL Script generated by MySQL Workbench
-- 06/02/15 13:18:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 1reko
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 1reko
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `1reko` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `1reko` ;

-- -----------------------------------------------------
-- Table `1reko`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1reko`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `1reko`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1reko`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `1reko`.`fruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1reko`.`fruta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
